# Generated by Django 3.1.6 on 2022-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
